<?php

namespace AppBundle\Repository;

/**
 * GradoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GradoRepository extends \Doctrine\ORM\EntityRepository
{
}
