prueba:
    resource: "@PruebaBundle/Controller/"
    type:     annotation
    prefix:   /

#fos_user:
#  resource: "@FOSUserBundle/Resources/config/routing/all.xml"

logout:
    path: /logout


app:
  resource: '@AppBundle/Controller/'
  type: annotation

home_page:
  path:     /homepage
  defaults: { _controller: AppBundle:Public:home }

login_page:
  path:     /loginpage
  defaults: { _controller: AppBundle:Public:login }
    
    
#user_edit:
#  path:  /user/edit/{id}
#  defaults: { _controller: AppBundle:Routing:edit }
  
user_edit:
  path:  /user/edit/{id}
  defaults: { _controller: AppBundle:Routing:edit }
  requirements:
    page: '\d+'
    
homepage_locale:
  path:      /ejemplo/locale/{_locale}
  defaults:  { _controller: AppBundle:Routing:locale, _locale: es }
  requirements:
      _locale:  es|en|fr
      
      
homepage_format:
  path:      /ejemplo/format/{_format}
  defaults:  { _controller: AppBundle:Routing:locale, _format: html }
