app_grado_apivoryx:
    resource: "@AppBundle/Controller/GradoRESTController.php"
    type:   rest
    prefix:   /apivoryx

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

app_alumno_apivoryx:
    resource: "@AppBundle/Controller/AlumnoRESTController.php"
    type:   rest
    prefix:   /apivoryx

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /sonata
    
_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /sonata

prueba:
    resource: "@PruebaBundle/Controller/"
    type:     annotation
    prefix:   /prueba

#fos_user:
#  resource: "@FOSUserBundle/Resources/config/routing/all.xml"

logout:
    path: /logout


app:
  resource: '@AppBundle/Controller/'
  type: annotation

home_page:
  path:     /homepage
  defaults: { _controller: AppBundle:Public:home }

login_page:
  path:     /loginpage
  defaults: { _controller: AppBundle:Public:login }
    
    
#user_edit:
#  path:  /user/edit/{id}
#  defaults: { _controller: AppBundle:Routing:edit }
  
user_edit:
  path:  /user/edit/{id}
  defaults: { _controller: AppBundle:Routing:edit }
  requirements:
    page: '\d+'
    
homepage_locale:
  path:      /ejemplo/locale/{_locale}
  defaults:  { _controller: AppBundle:Routing:locale, _locale: es }
  requirements:
      _locale:  es|en|fr
      
      
homepage_format:
  path:      /ejemplo/format/{_format}
  defaults:  { _controller: AppBundle:Routing:locale, _format: html }
  
asignaturas_rest:
  type:     rest
  resource: AppBundle\Controller\AsignaturasRESTController
