# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    providers:
        in_memory:
            memory:
                users:
                    carlos:
                        password: pass
                        roles: 'ROLE_USER'
                    admin:
                        password: word
                        roles: ['ROLE_ADMIN']
                        
#        mi_poveedor:
#            entity:
#                class: AppBundle:User
#                property: username
                
#        my_ldap:
#            ldap:
#                service: Symfony\Component\Ldap\Ldap
#                base_dn: ou=Users,dc=upm,dc=es
#                search_dn: ""
#                search_password: ""
#                default_roles: ROLE_USER
#                uid_key: uid
    
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
#        Symfony\Component\Security\Core\User\User:
#            algorithm: bcrypt
#            cost: 12
#        AppBundle\Entity\User:
#            algorithm: bcrypt
#            cost: 12
#        AppBundle\Entity\User: plaintext

    
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
#            http_basic: ~
            form_login:
                login_path: login
                check_path: login
                default_target_path: asignatura_index
                
#            form_login_ldap:
#                login_path: login
#                check_path: login
#                default_target_path: asignaturas
#                service: Symfony\Component\Ldap\Ldap
#                dn_string: 'uid={username},dc=example,dc=com'

#            http_basic_ldap:
#                # ...
#                service: Symfony\Component\Ldap\Ldap
#                dn_string: 'uid=curso,ou=Users,dc=upm,dc=es'
#                
#            provider: my_ldap
            logout:
                path:   /logout
                target: /home
        
    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/alumnocrud, roles: ROLE_ADMIN }
        - { path: ^/asignatura, roles: ROLE_USER }
#
#    access_decision_manager:
#        strategy: unanimous    

#security:
#    encoders:
#        FOS\UserBundle\Model\UserInterface: bcrypt
#
#    role_hierarchy:
#        ROLE_ADMIN:       ROLE_USER
#        ROLE_SUPER_ADMIN: ROLE_ADMIN
#
#    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
#    providers:
#        fos_userbundle:
#            id: fos_user.user_provider.username
#
#    firewalls:
#        dev:
#            pattern: ^/(_(profiler|wdt)|css|images|js)/
#            security: false
#            
#        main:
#            pattern: ^/
#            form_login:
#                provider: fos_userbundle
#                csrf_token_generator: security.csrf.token_manager
#                # if you are using Symfony < 2.8, use the following config instead:
#                # csrf_provider: form.csrf_provider
#
#            logout:       true
#            anonymous:    true
#
#    access_control:
#        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/admin/, role: ROLE_ADMIN }